#!/bin/bash

echo "🧹 Cleaning up unnecessary markdown files..."
echo ""

# Array of files to remove (duplicates and outdated)
files_to_remove=(
  "ARCHITECTURE.md"
  "CLOUDFLARE_API_TOKEN_GUIDE.md"
  "CLOUDFLARE_DEPLOY_GUIDE.md"
  "CLOUDFLARE_SECRETS_VISUAL.md"
  "CLOUDFLARE_SETUP_COMPLETE.md"
  "COMPLETE_DEPLOYMENT_CHECKLIST.md"
  "CURRENT_STATUS.md"
  "CUSTOM_DOMAIN_QUICK_REFERENCE.md"
  "DEPLOYMENT_AUTOMATION.md"
  "DEPLOYMENT_COMPLETE_GUIDE.md"
  "DEPLOYMENT_INFO.md"
  "DEPLOYMENT_README.md"
  "DEPLOYMENT_STATUS.md"
  "DEPLOYMENT_STATUS_UPDATED.md"
  "DEPLOYMENT_STATUS_FINAL.md"
  "DEPLOYMENT_VERIFICATION.md"
  "DEPLOY_ANSWER.md"
  "DEPLOY_CHEATSHEET.md"
  "DEPLOY_CHECKLIST.md"
  "DEPLOY_NOW.md"
  "DEPLOY_QUICK_START.md"
  "DEPLOY_TO_CLOUDFLARE_NOW.md"
  "DNS_ARCHITECTURE.md"
  "DNS_SETUP_GUIDE.md"
  "DNS_SETUP_VISUAL.md"
  "DNS_VISUAL_GUIDE.md"
  "DOCUMENTATION_SUMMARY.md"
  "DOGECOIN_INTEGRATION_IDEAS.md"
  "EXAMPLE_PROJECT_STRUCTURE.md"
  "FIXES_APPLIED.md"
  "FIX_BUILD_ERROR.md"
  "GETTING_STARTED.md"
  "GITHUB_ACTIONS_SETUP.md"
  "INSTALLER_FLOW_DIAGRAM.md"
  "INSTALLER_SUMMARY.md"
  "INSTALL_SERVER_VISUAL.md"
  "LEGAL_SAFETY_GUIDE.md"
  "LICENSE_AUDIT.md"
  "LOCAL_SETUP_GUIDE.md"
  "MACBOOK_DEPLOYMENT_STEPS.md"
  "MACBOOK_DEPLOY_GUIDE.md"
  "MACBOOK_QUICK_START.md"
  "OPEN_SOURCE_INFO.md"
  "QUICK_COMMANDS.md"
  "QUICK_DEPLOY_REFERENCE.md"
  "QUICK_SERVER_FIX.md"
  "QUICK_SERVER_TEST.md"
  "QUICK_START.md"
  "README_DEPLOYMENT.md"
  "SAXON_SERVER_DECISION.md"
  "SAXON_SERVER_SETUP.md"
  "SAXON_SERVER_SUMMARY.md"
  "SECRETS_SETUP_GUIDE.md"
  "SECURITY.md"
  "SERVER_CONNECTION_VISUAL.md"
  "SERVER_DOCUMENTATION_INDEX.md"
  "SERVER_INSTALL_1_PAGE.md"
  "SERVER_INSTALL_CHECKLIST.md"
  "SERVER_LOCAL_TEST_GUIDE.md"
  "SERVER_MANAGEMENT.md"
  "SERVER_QUICK_START.md"
  "SERVER_SETUP_QUICK_GUIDE.md"
  "SERVER_TEST_STATUS.md"
  "SIMPLE_DEPLOY_GUIDE.md"
  "START_HERE.md"
  "START_HERE_DEPLOYMENT.md"
  "START_HERE_NOW.md"
  "START_HERE_SERVER.md"
  "STATUS.md"
  "TESTING_INSTALLER.md"
  "WHATS_NEW_SERVER_INSTALLER.md"
  "XSLT_STATUS.md"
  "YOUR_REPO_STATUS.md"
  "DOCS_TO_KEEP.md"
)

# Remove each file
count=0
for file in "${files_to_remove[@]}"; do
  if [ -f "$file" ]; then
    rm -f "$file"
    echo "  ✓ Removed $file"
    ((count++))
  fi
done

echo ""
echo "✅ Cleanup complete! Removed $count files"
echo ""
echo "📚 Essential documentation kept:"
echo ""
echo "Main Docs:"
echo "  ✓ README.md - Project overview and quick start"
echo "  ✓ PRD.md - Product requirements document"
echo "  ✓ LICENSE - MIT license"
echo ""
echo "Deployment:"
echo "  ✓ DEPLOYMENT_GUIDE.md - Production deployment instructions"
echo ""
echo "Server (Optional):"
echo "  ✓ SERVER_INSTALL_GUIDE.md - Server installation"
echo "  ✓ SERVER_TROUBLESHOOTING_GUIDE.md - Server troubleshooting"
echo ""
echo "Technical:"
echo "  ✓ BROWSER_VS_SERVER.md - Architecture comparison"
echo "  ✓ SAXON_SERVER_ARCHITECTURE.md - Server technical details"
echo "  ✓ XSLT_SUPPORT_GUIDE.md - XSLT version support details"
echo "  ✓ LICENSE_SUMMARY.md - Open source compliance"
echo ""
echo "🎯 Documentation is now clean and organized!"
