#!/bin/bash

echo "🧹 Transio Project Cleanup Script"
echo "=================================="
echo ""
echo "This will remove 90+ unnecessary documentation files"
echo "while keeping essential project files."
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "Cleanup cancelled."
    exit 1
fi

echo ""
echo "Starting cleanup..."
echo ""

# Counter
REMOVED=0

# Function to remove file if it exists
remove_file() {
    if [ -f "$1" ]; then
        rm "$1"
        echo "✓ Removed: $1"
        ((REMOVED++))
    fi
}

# Remove duplicate/outdated deployment guides
remove_file "ARCHITECTURE.md"
remove_file "BROWSER_VS_SERVER.md"
remove_file "CLEANUP_NOW.md"
remove_file "CLEANUP_PLAN.md"
remove_file "CLOUDFLARE_API_TOKEN_GUIDE.md"
remove_file "CLOUDFLARE_DEPLOY_GUIDE.md"
remove_file "CLOUDFLARE_SECRETS_VISUAL.md"
remove_file "CLOUDFLARE_SETUP_COMPLETE.md"
remove_file "COMPLETE_DEPLOYMENT_CHECKLIST.md"
remove_file "CURRENT_STATUS.md"
remove_file "CUSTOM_DOMAIN_QUICK_REFERENCE.md"
remove_file "DEPLOYMENT_AUTOMATION.md"
remove_file "DEPLOYMENT_COMPLETE_GUIDE.md"
remove_file "DEPLOYMENT_GUIDE.md"
remove_file "DEPLOYMENT_INFO.md"
remove_file "DEPLOYMENT_README.md"
remove_file "DEPLOYMENT_STATUS.md"
remove_file "DEPLOYMENT_STATUS_FINAL.md"
remove_file "DEPLOYMENT_STATUS_UPDATED.md"
remove_file "DEPLOYMENT_VERIFICATION.md"
remove_file "DEPLOY_ANSWER.md"
remove_file "DEPLOY_CHEATSHEET.md"
remove_file "DEPLOY_CHECKLIST.md"
remove_file "DEPLOY_NOW.md"
remove_file "DEPLOY_QUICK_START.md"
remove_file "DEPLOY_TO_CLOUDFLARE_NOW.md"
remove_file "DNS_ARCHITECTURE.md"
remove_file "DNS_SETUP_GUIDE.md"
remove_file "DNS_SETUP_VISUAL.md"
remove_file "DNS_VISUAL_GUIDE.md"
remove_file "DOCS_TO_KEEP.md"
remove_file "DOCUMENTATION_SUMMARY.md"
remove_file "DOGECOIN_INTEGRATION_IDEAS.md"
remove_file "EXAMPLE_PROJECT_STRUCTURE.md"
remove_file "FINAL_CLEANUP_SUMMARY.md"
remove_file "FIXES_APPLIED.md"
remove_file "FIX_BUILD_ERROR.md"
remove_file "GETTING_STARTED.md"
remove_file "GITHUB_ACTIONS_SETUP.md"
remove_file "INSTALLER_FLOW_DIAGRAM.md"
remove_file "INSTALLER_SUMMARY.md"
remove_file "INSTALL_SERVER_VISUAL.md"
remove_file "LEGAL_SAFETY_GUIDE.md"
remove_file "LICENSE_AUDIT.md"
remove_file "LICENSE_SUMMARY.md"
remove_file "LOCAL_SETUP_GUIDE.md"
remove_file "MACBOOK_DEPLOYMENT_STEPS.md"
remove_file "MACBOOK_DEPLOY_GUIDE.md"
remove_file "MACBOOK_QUICK_START.md"
remove_file "OPEN_SOURCE_INFO.md"
remove_file "PRD.md"
remove_file "QUICK_COMMANDS.md"
remove_file "QUICK_DEPLOY_REFERENCE.md"
remove_file "QUICK_SERVER_FIX.md"
remove_file "QUICK_SERVER_TEST.md"
remove_file "QUICK_START.md"
remove_file "README_DEPLOYMENT.md"
remove_file "SAXON_SERVER_ARCHITECTURE.md"
remove_file "SAXON_SERVER_DECISION.md"
remove_file "SAXON_SERVER_SETUP.md"
remove_file "SAXON_SERVER_SUMMARY.md"
remove_file "SECRETS_SETUP_GUIDE.md"
remove_file "SECURITY.md"
remove_file "SERVER_CONNECTION_VISUAL.md"
remove_file "SERVER_DOCUMENTATION_INDEX.md"
remove_file "SERVER_INSTALL_1_PAGE.md"
remove_file "SERVER_INSTALL_CHECKLIST.md"
remove_file "SERVER_INSTALL_GUIDE.md"
remove_file "SERVER_LOCAL_TEST_GUIDE.md"
remove_file "SERVER_MANAGEMENT.md"
remove_file "SERVER_QUICK_START.md"
remove_file "SERVER_SETUP_QUICK_GUIDE.md"
remove_file "SERVER_TEST_STATUS.md"
remove_file "SERVER_TROUBLESHOOTING.md"
remove_file "SERVER_TROUBLESHOOTING_GUIDE.md"
remove_file "SIMPLE_DEPLOY_GUIDE.md"
remove_file "START_HERE.md"
remove_file "START_HERE_DEPLOYMENT.md"
remove_file "START_HERE_NOW.md"
remove_file "START_HERE_SERVER.md"
remove_file "STATUS.md"
remove_file "TESTING_INSTALLER.md"
remove_file "WHATS_NEW_SERVER_INSTALLER.md"
remove_file "XSLT_STATUS.md"
remove_file "XSLT_SUPPORT_GUIDE.md"
remove_file "YOUR_REPO_STATUS.md"

# Remove duplicate cleanup scripts
remove_file "cleanup-all.sh"
remove_file "cleanup-docs.sh"

# Remove unnecessary config files
remove_file "netlify.toml"
remove_file "vercel.json"
remove_file "runtime.config.json"
remove_file "spark.meta.json"
remove_file "theme.json"

# Remove old server management scripts (keeping only the main ones)
remove_file "start-server-dev.bat"
remove_file "start-server-dev.sh"
remove_file "test-server-setup.bat"
remove_file "test-server-setup.sh"
remove_file "server-manager.sh"

# Remove deployment-specific files not needed in source
remove_file "_headers"

echo ""
echo "=================================="
echo "✅ Cleanup Complete!"
echo "📊 Removed $REMOVED unnecessary files"
echo ""
echo "✓ Essential files kept:"
echo "  - README.md (main documentation)"
echo "  - LICENSE (open source license)"
echo "  - package.json, tsconfig.json, vite.config.ts"
echo "  - wrangler.toml (Cloudflare Pages config)"
echo "  - Server scripts (start/stop)"
echo "  - Launch scripts (Mac/Windows)"
echo ""
echo "Your project is now clean and deployment-ready! 🚀"
echo ""
